/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-06-22 02:14:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class delcaration04_jsp {

 int data; 
 
  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {


    try {
     
      out.write("\r\n");
      out.write("<!DOCTYPE html><html><head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>선언부:전역변수 및 메소드 선언</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    /* a 와 b는 로컬변수, 선언 및 초기화 후 사용  */
	int a=10;//로컬변수
    int b=a+data;

    out.println(b);

      out.write("\r\n");
      out.write("<!-- 전역변수 흐름의 후반에 작성해도 됨. \r\n");
      out.write(" 초기화를 하지않아도 데이타의 기본값으로 초기화 \r\n");
      out.write(" : 전역변수 -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    }
  }
}
